#!/bin/bash

# Generate environment file with GPU detection results
generate_env_file() {
    # Source the box_echo function
    source /app/scripts/box_echo.sh
    
    # Write GPU detection results to .env file for the application to use
    box_echo "Writing GPU detection results to '$APP_DATA_DIR/.env' file..."
    ENV_FILE="$APP_DATA_DIR/.env"

    # Remove any existing GPU-related variables (and the auto-generated header
    # comment) from .env file if it exists. This must happen BEFORE opening
    # $ENV_FILE for append below: the mv replaces the file with a new inode, so
    # anything already redirected to the old inode would be silently lost.
    # The header comment is stripped too, otherwise it accumulates on every boot.
    # The mv must NOT be gated on grep's exit status: grep returns 1 when it
    # selects no lines (e.g. a .env that only contains GPU_* entries), and a
    # `grep ... && mv` would then skip the replacement and leave the stale block
    # in place, reintroducing duplicates on the append below.
    # We DO distinguish grep's exit codes, though: 0 (matches) and 1 (no match)
    # are both success here, but >=2 means a real error (e.g. unreadable file)
    # and tmp may be empty/partial, so we must abort instead of mv-ing it over
    # $ENV_FILE and wiping unrelated settings.
    if [ -f "$ENV_FILE" ]; then
        grep -v -E "^# GPU Detection Results|^GPU_AVAILABLE_|^GPU_DEVICE_" "$ENV_FILE" > "${ENV_FILE}.tmp"
        grep_status=$?
        if [ "$grep_status" -le 1 ]; then
            mv "${ENV_FILE}.tmp" "$ENV_FILE"
        else
            box_echo "WARNING: failed to read '$ENV_FILE' (grep exit $grep_status); leaving it unchanged"
            rm -f "${ENV_FILE}.tmp"
        fi
    fi

    # Create or update the .env file with GPU variables
    {
        # Add GPU detection results
        echo "# GPU Detection Results - Auto-generated by entrypoint.sh"
        echo "GPU_AVAILABLE_NVIDIA=$GPU_AVAILABLE_NVIDIA"
        echo "GPU_AVAILABLE_INTEL=$GPU_AVAILABLE_INTEL"
        echo "GPU_AVAILABLE_AMD=$GPU_AVAILABLE_AMD"

        # Add device paths if they exist
        [ -n "$GPU_DEVICE_NVIDIA" ] && echo "GPU_DEVICE_NVIDIA=$GPU_DEVICE_NVIDIA"
        [ -n "$GPU_DEVICE_INTEL" ] && echo "GPU_DEVICE_INTEL=$GPU_DEVICE_INTEL"
        [ -n "$GPU_DEVICE_AMD" ] && echo "GPU_DEVICE_AMD=$GPU_DEVICE_AMD"

    } >> "$ENV_FILE"

    box_echo "GPU environment variables written to .env file"
}
