"""Add Media Status

Revision ID: 1cc1dd5dbe9f
Revises: 34f937f1d7b9
Create Date: 2024-09-17 13:27:49.217863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app_logger import ModuleLogger


# revision identifiers, used by Alembic.
revision: str = "1cc1dd5dbe9f"
down_revision: Union[str, None] = "34f937f1d7b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logging = ModuleLogger("AlembicMigrations")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum(
                    "DOWNLOADED",
                    "DOWNLOADING",
                    "MISSING",
                    "MONITORED",
                    name="monitorstatus",
                ),
                server_default="MISSING",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("media", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
