"""Add external URL to Connection

Revision ID: ba9a193d6e0e
Revises: a9320c7ab1a3
Create Date: 2025-12-12 18:26:36.967299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from app_logger import ModuleLogger

# revision identifiers, used by Alembic.
revision: str = "ba9a193d6e0e"
down_revision: Union[str, None] = "a9320c7ab1a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = ModuleLogger("AlembicMigrations")


def upgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("connection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "external_url",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="",
            )
        )

    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")


def downgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("connection", schema=None) as batch_op:
        batch_op.drop_column("external_url")

    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")
