"""add_new_fields_to_trailerprofile

Revision ID: f59986f4b718
Revises: 9606084facbe
Create Date: 2025-10-17 06:03:47.438378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from app_logger import ModuleLogger


# revision identifiers, used by Alembic.
revision: str = "f59986f4b718"
down_revision: Union[str, None] = "9606084facbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = ModuleLogger("AlembicMigrations")


def upgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trailerprofile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "stop_monitoring",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_trailer", sa.Boolean(), nullable=False, server_default="1"
            )
        )
        batch_op.add_column(
            sa.Column(
                "custom_folder",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="{media_folder}",
            )
        )
        batch_op.add_column(
            sa.Column(
                "notify_plex", sa.Boolean(), nullable=False, server_default="0"
            )
        )

    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")


def downgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trailerprofile", schema=None) as batch_op:
        batch_op.drop_column("notify_plex")
        batch_op.drop_column("custom_folder")
        batch_op.drop_column("is_trailer")
        batch_op.drop_column("stop_monitoring")

    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")
