"""Add Files tracking

Revision ID: 219bdc0e3cc9
Revises: ba9a193d6e0e
Create Date: 2025-12-28 23:36:11.943232

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from app_logger import ModuleLogger

# revision identifiers, used by Alembic.
revision: str = "219bdc0e3cc9"
down_revision: Union[str, None] = "ba9a193d6e0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = ModuleLogger("AlembicMigrations")


def upgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filefolderinfo",
        sa.Column(
            "type",
            sa.Enum("FILE", "FOLDER", "SYMLINK", name="filefoldertype"),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_trailer", sa.Boolean(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            name=op.f("fk_filefolderinfo_media_id_media"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["filefolderinfo.id"],
            name=op.f("fk_filefolderinfo_parent_id_filefolderinfo"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("filefolderinfo_pkc")),
    )
    with op.batch_alter_table("connection", schema=None) as batch_op:
        batch_op.alter_column(
            "external_url",
            existing_type=sa.VARCHAR(),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")


def downgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("connection", schema=None) as batch_op:
        batch_op.alter_column(
            "external_url",
            existing_type=sa.VARCHAR(),
            server_default=sa.text("('')"),
            existing_nullable=False,
        )

    op.drop_table("filefolderinfo")
    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")
