"""Add priority to Trailerprofile

Revision ID: 8c9a39658afa
Revises: 656a0b9cbe50
Create Date: 2025-06-16 01:29:20.386509

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app_logger import ModuleLogger

# revision identifiers, used by Alembic.
revision: str = "8c9a39658afa"
down_revision: Union[str, None] = "656a0b9cbe50"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logging = ModuleLogger("AlembicMigrations")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trailerprofile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "priority", sa.Integer(), server_default="0", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trailerprofile", schema=None) as batch_op:
        batch_op.drop_column("priority")

    # ### end Alembic commands ###
