"""Add notificationchannel table

Revision ID: 830eaf99eab5
Revises: fe3fa57174bc
Create Date: 2026-07-10 22:04:59.884524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from app_logger import ModuleLogger


# revision identifiers, used by Alembic.
revision: str = '830eaf99eab5'
down_revision: Union[str, None] = 'fe3fa57174bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = ModuleLogger("AlembicMigrations")


def upgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificationchannel',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('include_user_events', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('notificationchannel_pkc'))
    )
    with op.batch_alter_table('notificationchannel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificationchannel_name'), ['name'], unique=True)

    # ### end Alembic commands ###
    
    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")


def downgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificationchannel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificationchannel_name'))

    op.drop_table('notificationchannel')
    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")
