"""Add plex_section_key to pathmapping

Revision ID: e3a59c94c6dc
Revises: 443c82079368
Create Date: 2026-05-07 03:56:02.533217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from app_logger import ModuleLogger


# revision identifiers, used by Alembic.
revision: str = 'e3a59c94c6dc'
down_revision: Union[str, None] = '443c82079368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = ModuleLogger("AlembicMigrations")


def upgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathmapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plex_section_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")


def downgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathmapping', schema=None) as batch_op:
        batch_op.drop_column('plex_section_key')

    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")
