"""Add downloadattempt and startuppass tables

Revision ID: fe3fa57174bc
Revises: a1b2c3d4e5f6
Create Date: 2026-07-10 16:58:48.683694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from app_logger import ModuleLogger


# revision identifiers, used by Alembic.
revision: str = 'fe3fa57174bc'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = ModuleLogger("AlembicMigrations")


def upgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startuppass',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('startuppass_pkc'))
    )
    op.create_table('downloadattempt',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), server_default=sa.text("('default')"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_downloadattempt_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('downloadattempt_pkc')),
    sa.UniqueConstraint('media_id', 'profile_id', 'unit', name='uq_attempt_key')
    )
    with op.batch_alter_table('downloadattempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_downloadattempt_media_id'), ['media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_downloadattempt_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###
    
    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")


def downgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloadattempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_downloadattempt_profile_id'))
        batch_op.drop_index(batch_op.f('ix_downloadattempt_media_id'))

    op.drop_table('downloadattempt')
    op.drop_table('startuppass')
    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")
