export const environment = {
  production: true,
  apiUrl: 'api/v1/',
  customfilters: 'customfilters/',
  connections: 'connections/',
  files: 'files/',
  logs: 'logs/',
  media: 'media/',
  profiles: 'trailerprofiles/',
  settings: 'settings/',
  jobs: 'jobs/',
  tasks: 'tasks/',
  taskConfigs: 'task-configs/',
  tasksData: 'tasks-data',
  trailerprofiles: 'trailerprofiles/',
} as const;
