name: Build and Publish Devcontainer Pre-build

on:
  push:
    branches: [main]
    paths:
      - '.devcontainer/**'
  pull_request:
    branches: [main]
    paths:
      - '.devcontainer/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/devcontainer

jobs:
  build:
    name: Build and Publish Devcontainer Pre-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-

      - name: Build and push devcontainer pre-build
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          cacheFrom: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          platform: linux/amd64
          configFile: .devcontainer/devcontainer-prebuild.json
          push: always