name: Build and Publish Devcontainer Pre-build

on:
  push:
    branches: [main]
    paths:
      - '.devcontainer/**'
  pull_request:
    branches: [main]
    paths:
      - '.devcontainer/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/devcontainer

jobs:
  build:
    name: Build and Publish Devcontainer Pre-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare devcontainer configuration for prebuild
        run: |
          # Backup original devcontainer.json and use prebuild config
          mv .devcontainer/devcontainer.json .devcontainer/devcontainer-local.json
          mv .devcontainer/devcontainer-prebuild.json .devcontainer/devcontainer.json

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push devcontainer pre-build
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          cacheFrom: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          platform: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          skipContainerUserIdUpdate: true
          runCmd: |
            echo "Devcontainer pre-build completed successfully!"