name: Build and Deploy Docs
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml
  workflow_dispatch:  # Allows manual triggering of the workflow
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git Credentials
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for mkdocs-git-revision-date-localized-plugin

      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      # - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      # - uses: actions/cache@v4
      #   with:
      #     key: mkdocs-material-${{ env.cache_id }}
      #     path: .cache
      #     restore-keys: |
      #       mkdocs-material-
      - name: Install Dependencies
        run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs_github_changelog mkdocs-glightbox
      - name: Build and Deploy
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
